services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    ports: ["5678:5678"]
    environment:
      - N8N_BASIC_AUTH_USER=demo
      - N8N_BASIC_AUTH_PASSWORD=TechInterview2024!
      - GENERIC_TIMEZONE=Europe/Athens
      - TZ=Europe/Athens
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
    volumes:
      - n8n_data:/home/node/.n8n
      - ./workflows:/home/node/workflows

volumes:
  n8n_data:
